version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: primetrade-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - primetrade-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: primetrade-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/primetrade
      - JWT_SECRET_KEY=supersecretkey123
    depends_on:
      - mongo
    networks:
      - primetrade-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: primetrade-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - primetrade-network

volumes:
  mongo-data:

networks:
  primetrade-network:
    driver: bridge
